# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QStatusBar, QTableView, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(671, 417)
        MainWindow.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        MainWindow.setWindowTitle(u"Novastar MCTRL300 basic controller")
        self.menu_show_logs = QAction(MainWindow)
        self.menu_show_logs.setObjectName(u"menu_show_logs")
        self.menu_show_logs.setCheckable(True)
        self.menu_show_logs.setChecked(True)
#if QT_CONFIG(shortcut)
        self.menu_show_logs.setShortcut(u"Ctrl+Shift+L")
#endif // QT_CONFIG(shortcut)
        self.menu_about = QAction(MainWindow)
        self.menu_about.setObjectName(u"menu_about")
#if QT_CONFIG(shortcut)
        self.menu_about.setShortcut(u"Ctrl+Shift+A")
#endif // QT_CONFIG(shortcut)
        self.brightness_1_pct = QAction(MainWindow)
        self.brightness_1_pct.setObjectName(u"brightness_1_pct")
        self.brightness_5_pct = QAction(MainWindow)
        self.brightness_5_pct.setObjectName(u"brightness_5_pct")
        self.brightness_50_pct = QAction(MainWindow)
        self.brightness_50_pct.setObjectName(u"brightness_50_pct")
        self.brightness_100_pct = QAction(MainWindow)
        self.brightness_100_pct.setObjectName(u"brightness_100_pct")
        self.pattern_live = QAction(MainWindow)
        self.pattern_live.setObjectName(u"pattern_live")
        self.pattern_red = QAction(MainWindow)
        self.pattern_red.setObjectName(u"pattern_red")
        self.pattern_green = QAction(MainWindow)
        self.pattern_green.setObjectName(u"pattern_green")
        self.pattern_blue = QAction(MainWindow)
        self.pattern_blue.setObjectName(u"pattern_blue")
        self.pattern_white = QAction(MainWindow)
        self.pattern_white.setObjectName(u"pattern_white")
        self.pattern_cycle_colors = QAction(MainWindow)
        self.pattern_cycle_colors.setObjectName(u"pattern_cycle_colors")
        self.pattern_slash = QAction(MainWindow)
        self.pattern_slash.setObjectName(u"pattern_slash")
        self.pattern_black = QAction(MainWindow)
        self.pattern_black.setObjectName(u"pattern_black")
        self.pattern_black.setEnabled(False)
        self.pattern_freeze = QAction(MainWindow)
        self.pattern_freeze.setObjectName(u"pattern_freeze")
        self.pattern_freeze.setEnabled(False)
        self.brightness_up = QAction(MainWindow)
        self.brightness_up.setObjectName(u"brightness_up")
        self.brightness_down = QAction(MainWindow)
        self.brightness_down.setObjectName(u"brightness_down")
        self.pattern_next = QAction(MainWindow)
        self.pattern_next.setObjectName(u"pattern_next")
        self.pattern_previous = QAction(MainWindow)
        self.pattern_previous.setObjectName(u"pattern_previous")
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.v_layout_port = QVBoxLayout()
        self.v_layout_port.setObjectName(u"v_layout_port")
        self.v_layout_port.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        font = QFont()
        font.setFamilies([u"DejaVu Sans"])
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setText(u"Select serial port to controller:")

        self.v_layout_port.addWidget(self.label_2)

        self.tbl_serial_ports = QTableView(self.centralwidget)
        self.tbl_serial_ports.setObjectName(u"tbl_serial_ports")
        self.tbl_serial_ports.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tbl_serial_ports.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tbl_serial_ports.setTabKeyNavigation(False)
        self.tbl_serial_ports.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.tbl_serial_ports.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tbl_serial_ports.setWordWrap(False)
        self.tbl_serial_ports.horizontalHeader().setVisible(True)
        self.tbl_serial_ports.verticalHeader().setVisible(False)

        self.v_layout_port.addWidget(self.tbl_serial_ports)

        self.btn_serial_open = QPushButton(self.centralwidget)
        self.btn_serial_open.setObjectName(u"btn_serial_open")
        self.btn_serial_open.setText(u"Open selected port")
        self.btn_serial_open.setCheckable(True)

        self.v_layout_port.addWidget(self.btn_serial_open)

        self.btn_serial_refresh = QPushButton(self.centralwidget)
        self.btn_serial_refresh.setObjectName(u"btn_serial_refresh")
        self.btn_serial_refresh.setEnabled(False)

        self.v_layout_port.addWidget(self.btn_serial_refresh)

        self.lbl_serial_status = QLabel(self.centralwidget)
        self.lbl_serial_status.setObjectName(u"lbl_serial_status")
        self.lbl_serial_status.setFrameShape(QFrame.Shape.Box)
        self.lbl_serial_status.setText(u"No port")
        self.lbl_serial_status.setTextFormat(Qt.TextFormat.PlainText)
        self.lbl_serial_status.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.v_layout_port.addWidget(self.lbl_serial_status)

        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.v_layout_port.addWidget(self.line_3)

        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.label_7.setFont(font1)
        self.label_7.setText(u"Screen connected to output:")

        self.v_layout_port.addWidget(self.label_7)

        self.cmb_output = QComboBox(self.centralwidget)
        self.cmb_output.setObjectName(u"cmb_output")
        self.cmb_output.setMinimumSize(QSize(0, 20))
        self.cmb_output.setToolTipDuration(5)
        self.cmb_output.setEditable(False)
        self.cmb_output.setMaxVisibleItems(2)

        self.v_layout_port.addWidget(self.cmb_output)


        self.horizontalLayout.addLayout(self.v_layout_port)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout.addWidget(self.line)

        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout.addWidget(self.line_2)

        self.h_layout_settings = QHBoxLayout()
        self.h_layout_settings.setObjectName(u"h_layout_settings")
        self.HLayoutSettings_dummy = QHBoxLayout()
        self.HLayoutSettings_dummy.setObjectName(u"HLayoutSettings_dummy")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.grp_brightness = QGroupBox(self.centralwidget)
        self.grp_brightness.setObjectName(u"grp_brightness")
        self.grp_brightness.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sldr_brightness = QSlider(self.grp_brightness)
        self.sldr_brightness.setObjectName(u"sldr_brightness")
        self.sldr_brightness.setEnabled(False)
        self.sldr_brightness.setGeometry(QRect(10, 30, 70, 281))
        self.sldr_brightness.setMinimumSize(QSize(70, 0))
        self.sldr_brightness.setCursor(QCursor(Qt.CursorShape.ClosedHandCursor))
        self.sldr_brightness.setAutoFillBackground(False)
        self.sldr_brightness.setMaximum(255)
        self.sldr_brightness.setValue(8)
        self.sldr_brightness.setSliderPosition(8)
        self.sldr_brightness.setOrientation(Qt.Orientation.Vertical)
        self.sldr_brightness.setInvertedAppearance(False)
        self.sldr_brightness.setTickPosition(QSlider.TickPosition.NoTicks)
        self.sldr_brightness.setTickInterval(10)
        self.lbl_brightness_value = QLabel(self.grp_brightness)
        self.lbl_brightness_value.setObjectName(u"lbl_brightness_value")
        self.lbl_brightness_value.setGeometry(QRect(0, 320, 97, 20))
        self.lbl_brightness_value.setMaximumSize(QSize(16777215, 20))
        self.lbl_brightness_value.setBaseSize(QSize(0, 20))
        self.lbl_brightness_value.setText(u"Unknown")
        self.lbl_brightness_value.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.grp_brightness)


        self.HLayoutSettings_dummy.addLayout(self.verticalLayout_3)

        self.grp_patterns = QGroupBox(self.centralwidget)
        self.grp_patterns.setObjectName(u"grp_patterns")
        self.grp_patterns.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_patterns.sizePolicy().hasHeightForWidth())
        self.grp_patterns.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setBold(False)
        self.grp_patterns.setFont(font2)
        self.grp_patterns.setStyleSheet(u"border: none")
        self.grp_patterns.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.grp_patterns.setFlat(True)
        self.layoutWidget = QWidget(self.grp_patterns)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 20, 112, 260))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(5, 0, 0, 0)
        self.btn_normal = QRadioButton(self.layoutWidget)
        self.btn_normal.setObjectName(u"btn_normal")
        self.btn_normal.setText(u"Live (input)")

        self.verticalLayout.addWidget(self.btn_normal)

        self.btn_red = QRadioButton(self.layoutWidget)
        self.btn_red.setObjectName(u"btn_red")
        self.btn_red.setText(u"Red")

        self.verticalLayout.addWidget(self.btn_red)

        self.btn_green = QRadioButton(self.layoutWidget)
        self.btn_green.setObjectName(u"btn_green")
        self.btn_green.setText(u"Green")

        self.verticalLayout.addWidget(self.btn_green)

        self.btn_blue = QRadioButton(self.layoutWidget)
        self.btn_blue.setObjectName(u"btn_blue")
        self.btn_blue.setText(u"Blue")

        self.verticalLayout.addWidget(self.btn_blue)

        self.btn_white = QRadioButton(self.layoutWidget)
        self.btn_white.setObjectName(u"btn_white")
        self.btn_white.setText(u"White")

        self.verticalLayout.addWidget(self.btn_white)

        self.btn_cycle_colors = QRadioButton(self.layoutWidget)
        self.btn_cycle_colors.setObjectName(u"btn_cycle_colors")
        self.btn_cycle_colors.setText(u"Cycle colors")

        self.verticalLayout.addWidget(self.btn_cycle_colors)

        self.btn_slash = QRadioButton(self.layoutWidget)
        self.btn_slash.setObjectName(u"btn_slash")
        self.btn_slash.setText(u"Slash")

        self.verticalLayout.addWidget(self.btn_slash)

        self.btn_blackout = QRadioButton(self.layoutWidget)
        self.btn_blackout.setObjectName(u"btn_blackout")
        self.btn_blackout.setEnabled(False)
        self.btn_blackout.setText(u"Blackout")

        self.verticalLayout.addWidget(self.btn_blackout)

        self.btn_freeze = QRadioButton(self.layoutWidget)
        self.btn_freeze.setObjectName(u"btn_freeze")
        self.btn_freeze.setEnabled(False)
        self.btn_freeze.setText(u"Freeze")

        self.verticalLayout.addWidget(self.btn_freeze)


        self.HLayoutSettings_dummy.addWidget(self.grp_patterns)


        self.h_layout_settings.addLayout(self.HLayoutSettings_dummy)


        self.horizontalLayout.addLayout(self.h_layout_settings)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 671, 22))
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menuBrightness = QMenu(self.menubar)
        self.menuBrightness.setObjectName(u"menuBrightness")
        self.menuBrightness.setEnabled(True)
        self.menuPattern = QMenu(self.menubar)
        self.menuPattern.setObjectName(u"menuPattern")
        self.menuPattern.setEnabled(True)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.btn_serial_open, self.cmb_output)
        QWidget.setTabOrder(self.cmb_output, self.btn_serial_refresh)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPattern.menuAction())
        self.menubar.addAction(self.menuBrightness.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_help.addAction(self.menu_show_logs)
        self.menu_help.addAction(self.menu_about)
        self.menuBrightness.addAction(self.brightness_1_pct)
        self.menuBrightness.addAction(self.brightness_5_pct)
        self.menuBrightness.addAction(self.brightness_50_pct)
        self.menuBrightness.addAction(self.brightness_100_pct)
        self.menuBrightness.addSeparator()
        self.menuBrightness.addAction(self.brightness_up)
        self.menuBrightness.addAction(self.brightness_down)
        self.menuPattern.addAction(self.pattern_live)
        self.menuPattern.addAction(self.pattern_red)
        self.menuPattern.addAction(self.pattern_green)
        self.menuPattern.addAction(self.pattern_blue)
        self.menuPattern.addAction(self.pattern_white)
        self.menuPattern.addAction(self.pattern_cycle_colors)
        self.menuPattern.addAction(self.pattern_slash)
        self.menuPattern.addAction(self.pattern_black)
        self.menuPattern.addAction(self.pattern_freeze)
        self.menuPattern.addSeparator()
        self.menuPattern.addAction(self.pattern_next)
        self.menuPattern.addAction(self.pattern_previous)
        self.menuFile.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)

        self.cmb_output.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.menu_show_logs.setText(QCoreApplication.translate("MainWindow", u"Show &logs", None))
        self.menu_about.setText(QCoreApplication.translate("MainWindow", u"&About", None))
        self.brightness_1_pct.setText(QCoreApplication.translate("MainWindow", u"1%", None))
#if QT_CONFIG(shortcut)
        self.brightness_1_pct.setShortcut(QCoreApplication.translate("MainWindow", u"1", None))
#endif // QT_CONFIG(shortcut)
        self.brightness_5_pct.setText(QCoreApplication.translate("MainWindow", u"5%", None))
#if QT_CONFIG(shortcut)
        self.brightness_5_pct.setShortcut(QCoreApplication.translate("MainWindow", u"2", None))
#endif // QT_CONFIG(shortcut)
        self.brightness_50_pct.setText(QCoreApplication.translate("MainWindow", u"50%", None))
#if QT_CONFIG(shortcut)
        self.brightness_50_pct.setShortcut(QCoreApplication.translate("MainWindow", u"5", None))
#endif // QT_CONFIG(shortcut)
        self.brightness_100_pct.setText(QCoreApplication.translate("MainWindow", u"100%", None))
#if QT_CONFIG(shortcut)
        self.brightness_100_pct.setShortcut(QCoreApplication.translate("MainWindow", u"0", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_live.setText(QCoreApplication.translate("MainWindow", u"Live", None))
#if QT_CONFIG(shortcut)
        self.pattern_live.setShortcut(QCoreApplication.translate("MainWindow", u"N", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_red.setText(QCoreApplication.translate("MainWindow", u"Red", None))
#if QT_CONFIG(shortcut)
        self.pattern_red.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_green.setText(QCoreApplication.translate("MainWindow", u"Green", None))
#if QT_CONFIG(shortcut)
        self.pattern_green.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_blue.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
#if QT_CONFIG(shortcut)
        self.pattern_blue.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_white.setText(QCoreApplication.translate("MainWindow", u"White", None))
#if QT_CONFIG(shortcut)
        self.pattern_white.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_cycle_colors.setText(QCoreApplication.translate("MainWindow", u"Cycle colors", None))
#if QT_CONFIG(shortcut)
        self.pattern_cycle_colors.setShortcut(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_slash.setText(QCoreApplication.translate("MainWindow", u"Slash", None))
#if QT_CONFIG(shortcut)
        self.pattern_slash.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_black.setText(QCoreApplication.translate("MainWindow", u"Blackout", None))
        self.pattern_freeze.setText(QCoreApplication.translate("MainWindow", u"Freeze", None))
        self.brightness_up.setText(QCoreApplication.translate("MainWindow", u"Brightness up", None))
#if QT_CONFIG(shortcut)
        self.brightness_up.setShortcut(QCoreApplication.translate("MainWindow", u"Up", None))
#endif // QT_CONFIG(shortcut)
        self.brightness_down.setText(QCoreApplication.translate("MainWindow", u"Brightness down", None))
#if QT_CONFIG(shortcut)
        self.brightness_down.setShortcut(QCoreApplication.translate("MainWindow", u"Down", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_next.setText(QCoreApplication.translate("MainWindow", u"Next pattern", None))
#if QT_CONFIG(shortcut)
        self.pattern_next.setShortcut(QCoreApplication.translate("MainWindow", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.pattern_previous.setText(QCoreApplication.translate("MainWindow", u"Previous pattern", None))
#if QT_CONFIG(shortcut)
        self.pattern_previous.setShortcut(QCoreApplication.translate("MainWindow", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
        self.btn_serial_refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh ports list", None))
#if QT_CONFIG(tooltip)
        self.cmb_output.setToolTip(QCoreApplication.translate("MainWindow", u"Select which controller output is connected to the screen", None))
#endif // QT_CONFIG(tooltip)
        self.cmb_output.setCurrentText("")
        self.grp_brightness.setTitle(QCoreApplication.translate("MainWindow", u"Brightness", None))
        self.grp_patterns.setTitle(QCoreApplication.translate("MainWindow", u"Pattern/Label:", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuBrightness.setTitle(QCoreApplication.translate("MainWindow", u"Brightness", None))
        self.menuPattern.setTitle(QCoreApplication.translate("MainWindow", u"Pattern", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        pass
    # retranslateUi

